spring.data.mongodb.connection-string=mongodb://admin:password@localhost:27017/datawarehouse?authSource=admin
spring.application.name=datawarehouse
marketdata.api.base-url=https://data.nasdaq.com/api/v3
marketdata.api.key=${API_KEY}
marketdata.api.table=QDL/BITFINEX
marketdata.api.code=ZRXUSD
marketdata.extractor.mode=real
server.port=8081

